server:
  port: 8081

spring:
  application:
    name: account-management-service

  datasource:
    url: jdbc:postgresql://localhost:5434/account_service_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: false

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method

logging:
  level:
    com.sportlink.account: INFO
    org.hibernate.SQL: INFO
